travis:
  secure:
    BINSTAR_TOKEN: Coa7zmiqdzF0dWOV6yK9KyTNTdQRQfbI+/r7Vey6xwRTITYaUsO7lfXQlzp9ATDC+wA2IM2LEJBRt/B0KwazcqpcsnUd1M0PweicGbOzM1RYT9MbhHAJm9dw++kYHHYZI3PiiswH4q7w10Lg5dcyHK2qeW12eXQjiDOMf6H4Cy+i3a5/BuLglQZMqS4bF3bgH2rVaMyehbiFlJkYbYgLu9wG9NDIjdJ6NRUxqoyMvNjg6LQeQ3YbD/wh7oLxAZh5NkjPl2cDKeVH5q8wbu1YxB++hGAvahMhUxVrhe+CUjnQ3IjPDrQiT1EKNM/QI1GweJfLrCNIgQbYSaALovEuZJ2l48hrwZan3oomI0XBzo/LKQcfLwQmfvgL3o6JngXRHcpdji+R2xHoM5rSe9jQf/MqYyqOvUO0sfba0e7+Iqo4aVqJyVfNQ+1+MZIqv4rhga2Oru40H+k2yhLUKgcmMKTXmmFLi78eeqWHp2tQgko+yUONboak/BX/IT3rbul9j0I867ZFxELinxxAwhbyhXrp6yfg5r5I/QwYechkDEA4uIgfNQbjJkQhPWWk6EoOvSB4ET5VBFR4N0pxIQvZVeqkyi7of2UiDVIvIUPrbVBw/AchcA7lZxEWEMGlHMyeEfcXIIGSJQUJkX+2VhObisWpdlz+rYncaZ564JJGNKc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
